name: First Workflow
on: workflow_dispatch

jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print start
        run: echo "hello"
      - name: Print goodbye
        run: echo "done --bye!"

