name: work flow
on: workflow_dispatch

jobs:
  secondjob:
    
    runs-on: ubuntu-latest
    
    steps:  
      - name: list all files
        run: ls
  thirdjob:
    runs-on: ubuntu-latest
    steps:
      - name: print start
        run: echo "start"
      
  
